image: maven:3.6.3-jdk-11

stages:
  - build

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .m2/repository/

build-job:
  stage: build
  variables:
    BUILD_OUTPUT_PATH: ./releng/com.thalesgroup.mde.capella.stpa.update/target
    MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
    OUTPUT_FOLDER: output
  script:
    - |
      TP_VERSIONS=("5.0" "5.1" "5.2" "6.0" "6.1")
      mkdir ${OUTPUT_FOLDER}
      for v in ${TP_VERSIONS[@]}; do
        echo '********** BUILDING FOR CAPELLA '${v}' **********'
        mvn clean package -P capella-${v} -Declipse.p2.mirrors=false
        mv ${BUILD_OUTPUT_PATH}/STPA*.zip ./${OUTPUT_FOLDER}
      done
  artifacts:
    paths:
      - ${OUTPUT_FOLDER}
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - features/**/*
        - plugins/**/*
        - releng/**/*
        - doc/**/*
        - "**/pom.xml"
